/**
 * InstinctController — stateless logic controller for runtime-generated behavior primitives.
 *
 * WHY THIS EXISTS (spec §1): the LLM agent receives a flat vocabulary of atomic actions and must
 * plan multi-step behavior itself. An **instinct** is a high-level behavior whose name and action
 * list are generated by code at runtime from the action registry and the entity's live capabilities.
 * The LLM calls the instinct; the server does the actions (parameter resolution, ordering,
 * validation, dispatch through the existing pipeline).
 *
 * Placement rationale (per controller_patterns.md §4 and system_map.md):
 *   - Logic controller (not a util): reads the live facade (capability gate, entity positions).
 *   - In `controllers/ai/`: NPC behavior logic — the LLM-side twin of the deterministic brain.
 *   - Stateless: no owned state, no broadcast, no persistence schema change.
 *
 * Public API:
 *   - generateForEntity(entityId): Array<Instinct>  (never throws)
 *   - expand(entityId, instinctName, { targetEntityId? }): { ok, instinctName, steps? | code, error }
 *
 * @module InstinctController
 */

import Logger from '../../utils/Logger.js';
import { NPC_BEHAVIOR_CHASE_ATTACK } from '../../utils/Constants.js';
import { ACTION_NAMES } from '../../../shared/ActionVocabulary.js';
import { TRAIT_GROUPS, STAT_NAMES, EXISTENCE_GONE_AT, flatKey } from '../../../shared/StatVocabulary.js';
import { ID_PREFIXES, isPrefixed } from '../../../shared/IdPrefixes.js';

/**
 * Flat "trait.stat" key for Physical.existence — derived from the shared
 * stat vocabulary so the `stats[<key>]` lookup key can never drift from
 * data/traits.json (reproduces the `stats['Physical.existence']` format).
 * @constant
 */
const EXISTENCE_FLAT_KEY = flatKey(TRAIT_GROUPS.PHYSICAL, STAT_NAMES.EXISTENCE);

// ─────────────────────────────────────────────
// Code-level constants (per spec §2.3, §3)
// ─────────────────────────────────────────────

/**
 * Role → word map for name composition (spec §3.1).
 * @constant
 */
const ROLE_WORDS = {
    movement: 'chase',
    attack: 'attack'
};

/**
 * Role → phrase template for description generation (spec §2.3, item 4).
 * @constant
 */
const ROLE_PHRASES = {
    movement: 'move toward the target ({action})',
    attack: 'attack the target ({action})'
};

/**
 * Behavior templates — each template defines roles, candidates, and role type.
 * Only `chase_attack` ships (spec §2.3).
 * @constant
 */
const TEMPLATES = [
    {
        key: NPC_BEHAVIOR_CHASE_ATTACK,
        roles: [
            { role: 'movement', candidates: [ACTION_NAMES.MOVE, ACTION_NAMES.DASH] },
            { role: 'attack', candidates: [ACTION_NAMES.PUNCH, ACTION_NAMES.CUT, ACTION_NAMES.SHOOT_T1] }
        ]
    }
];

/**
 * Max steps per instinct expansion (spec §2.4).
 * @constant
 */
const MAX_INSTINCT_STEPS = 5;

// ─────────────────────────────────────────────
// Helper utilities
// ─────────────────────────────────────────────

/**
 * Sanitize a string to snake_case for fallback word generation (spec §3.2).
 * @param {string} str
 * @returns {string}
 */
function sanitizeToSnakeCase(str) {
    return str
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');
}

/**
 * Resolve the best action for a role from the capability snapshot.
 * Returns the action name or null if none executable.
 * @param {string} entityId
 * @param {string[]} candidates
 * @param {Object} actionsSnapshot — { [actionName]: { canExecute: Array<{score: number}> } }
 * @returns {string|null}
 */
function pickBestAction(entityId, candidates, actionsSnapshot) {
    let best = null;
    let bestScore = -Infinity;

    for (const name of candidates) {
        const entry = actionsSnapshot[name];
        if (!entry || !entry.canExecute || entry.canExecute.length === 0) {
            continue;
        }
        // Best score among all capability entries for this action
        const score = Math.max(...entry.canExecute.map(e => e.score ?? 0));
        if (score > bestScore) {
            bestScore = score;
            best = name;
        }
        // Tie-break: registry order — candidates are listed in priority order,
        // so the first one with the best score wins (stable).
    }

    return best;
}

/**
 * Check if a spatial object has finite coordinates.
 * @param {Object|null} spatial
 * @returns {boolean}
 */
function isFiniteSpatial(spatial) {
    if (!spatial || typeof spatial !== 'object') return false;
    return Number.isFinite(spatial.x) && Number.isFinite(spatial.y);
}

/**
 * Resolve the target component for an attack action.
 * Returns the first usable component with existence >= 1, or null.
 * @param {Object} entity
 * @returns {string|null}
 */
function pickTargetComponent(entity) {
    if (!entity || !Array.isArray(entity.components)) return null;

    // First pass: find component with existence >= 1
    for (const comp of entity.components) {
        const compId = comp.id;
        const compData = entity._components?.[compId];
        const stats = compData?.stats ?? comp.stats;
        if (stats) {
            const dur = stats[EXISTENCE_FLAT_KEY] ?? 0;
            if (dur > EXISTENCE_GONE_AT) {
                return compId;
            }
        }
    }

    // Second pass: first usable component with existence >= 1 (fallback for non-standard stats)
    for (const comp of entity.components) {
        const compId = comp.id;
        const compData = entity._components?.[compId];
        const stats = compData?.stats ?? comp.stats;
        // Still require existence >= 1, or no existence stat at all (assumed usable)
        if (stats) {
            const dur = stats[EXISTENCE_FLAT_KEY];
            if (dur === undefined || dur > EXISTENCE_GONE_AT) {
                return compId;
            }
        } else {
            // No stats at all — assumed usable
            return compId;
        }
    }

    return null;
}

/**
 * Resolve the source component for an action (best-scoring canExecute entry).
 * @param {Object} actionsSnapshot
 * @param {string} actionName
 * @returns {string|null}
 */
function pickSourceComponent(actionsSnapshot, actionName) {
    const entry = actionsSnapshot[actionName];
    if (!entry || !entry.canExecute || entry.canExecute.length === 0) return null;

    // Pick source from the best-scoring canExecute entry
    let bestEntry = null;
    let bestScore = -Infinity;
    for (const ce of entry.canExecute) {
        if ((ce.score ?? 0) > bestScore) {
            bestScore = ce.score ?? 0;
            bestEntry = ce;
        }
    }

    return bestEntry?.componentId ?? null;
}

// ─────────────────────────────────────────────
// InstinctController class
// ─────────────────────────────────────────────

class InstinctController {
    /**
     * @param {Object} deps
     * @param {Object} deps.actionRegistry — data/actions.json
     */
    constructor({ actionRegistry }) {
        this._actionRegistry = actionRegistry || {};
        this._facade = null;
    }

    /**
     * Lazy facade reference injection (per controller_patterns.md §4).
     * @param {Object} facade — WorldStateController
     */
    setWorldStateController(facade) {
        this._facade = facade;
    }

    /**
     * (a) GENERATION — live per call, never throws (returns [] on any facade error).
     *
     * For each template, resolves one action per role from the capability snapshot,
     * composes a name, generates a description, and runs collision avoidance.
     *
     * @param {string} entityId
     * @returns {Array<{ name: string, description: string, roles: Array<{ role: string, word: string, action: string }> }>}
     */
    generateForEntity(entityId) {
        try {
            // One snapshot per generation (spec §2.3, cost note)
            const actionsData = this._facade.getActionsForEntity(entityId);
            if (!actionsData || typeof actionsData !== 'object') {
                return [];
            }

            const results = [];

            for (const template of TEMPLATES) {
                const resolvedRoles = [];

                for (const roleDef of template.roles) {
                    const actionName = pickBestAction(entityId, roleDef.candidates, actionsData);
                    if (!actionName) continue; // Role with no executable candidate contributes nothing

                    const word = ROLE_WORDS[roleDef.role] || sanitizeToSnakeCase(roleDef.role);
                    resolvedRoles.push({
                        role: roleDef.role,
                        word,
                        action: actionName
                    });
                }

                if (resolvedRoles.length === 0) continue; // No role resolved → no entry

                // Name composition (spec §3.1)
                const name = resolvedRoles.map(r => r.word).join('_');

                // Description generation (spec §2.3, item 4)
                const phrases = resolvedRoles.map(r => {
                    const template = ROLE_PHRASES[r.role] || '{action}';
                    return template.replace('{action}', r.action);
                });
                const description = phrases.join(', then ');

                results.push({ name, description, roles: resolvedRoles });
            }

            // Collision pass (spec §3.5)
            return this._resolveCollisions(results, entityId);

        } catch (err) {
            Logger.warn(`[InstinctController] generateForEntity failed for ${entityId}:`, err.message);
            return [];
        }
    }

    /**
     * Collision avoidance: ensure unique names within the set and no collision with action registry.
     * @param {Array<Object>} instincts
     * @param {string} entityId
     * @returns {Array<Object>}
     */
    _resolveCollisions(instincts, entityId) {
        const seen = new Set();
        const registryNames = new Set(Object.keys(this._actionRegistry));
        const result = [];

        for (const instinct of instincts) {
            let name = instinct.name;
            let suffix = 2;

            while (seen.has(name) || registryNames.has(name)) {
                name = instinct.name + '_' + suffix;
                suffix++;
            }

            seen.add(name);
            result.push({ ...instinct, name });
        }

        return result;
    }

    /**
     * (b) EXPANSION — live re-resolution at dispatch time.
     *
     * @param {string} entityId
     * @param {string} instinctName
     * @param {Object} [options]
     * @param {string} [options.targetEntityId]
     * @returns {{ ok: true, instinctName: string, targetEntityId: string|null, steps: Array<{ actionName: string, params: Object }> }
     *           |{ ok: false, instinctName: string, code: string, error: string }}
     */
    expand(entityId, instinctName, options = {}) {
        try {
            const { targetEntityId = null } = options;

            // Find the instinct in generation output
            const instincts = this.generateForEntity(entityId);
            const instinct = instincts.find(i => i.name === instinctName);
            if (!instinct) {
                return {
                    ok: false,
                    instinctName,
                    code: 'UNKNOWN_INSTINCT',
                    error: `Unknown instinct "${instinctName}"`
                };
            }

            // Target resolution
            const resolvedTarget = this._resolveTarget(entityId, targetEntityId);
            if (!resolvedTarget.ok) {
                return {
                    ok: false,
                    instinctName,
                    code: resolvedTarget.code,
                    error: resolvedTarget.error
                };
            }

            const target = resolvedTarget.entity;
            const targetEntityIdResolved = resolvedTarget.entityId;

            // Build steps (spec §2.4)
            const steps = [];

            for (const roleEntry of instinct.roles) {
                if (steps.length >= MAX_INSTINCT_STEPS) break;

                const actionName = roleEntry.action;

                // Per-step pre-validation (spec §2.4 abort rule)
                if (!this._actionRegistry[actionName]) {
                    // Action not in registry — drop and abort dependents
                    break;
                }

                let params = {};

                if (roleEntry.role === 'movement') {
                    params = {
                        targetX: target.spatial.x,
                        targetY: target.spatial.y
                    };
                } else if (roleEntry.role === 'attack') {
                    const targetComponentId = pickTargetComponent(target);
                    if (targetComponentId === null) {
                        // No usable target component — drop attack step
                        continue;
                    }
                    const componentId = pickSourceComponent(
                        this._facade.getActionsForEntity(entityId),
                        actionName
                    );
                    if (!componentId) {
                        break; // No source component — abort
                    }
                    params = {
                        targetEntityId: targetEntityIdResolved,
                        targetComponentId,
                        componentId
                    };
                }

                // Add reserved internal key
                params._instinct = instinctName;

                steps.push({ actionName, params });
            }

            if (steps.length === 0) {
                return {
                    ok: false,
                    instinctName,
                    code: 'NO_EXECUTABLE_STEPS',
                    error: 'No executable steps after expansion'
                };
            }

            return {
                ok: true,
                instinctName,
                targetEntityId: targetEntityIdResolved,
                steps
            };

        } catch (err) {
            Logger.warn(`[InstinctController] expand failed for ${entityId}/${instinctName}:`, err.message);
            return {
                ok: false,
                instinctName,
                code: 'UNKNOWN_INSTINCT',
                error: err.message
            };
        }
    }

    /**
     * Resolve the target entity for expansion.
     * @param {string} npcEntityId
     * @param {string|null} providedTargetId
     * @returns {{ ok: boolean, entity?: Object, entityId?: string|null, code?: string, error?: string }}
     */
    _resolveTarget(npcEntityId, providedTargetId) {
        // If no target provided, find nearest eligible entity in same room
        if (providedTargetId === null || providedTargetId === undefined) {
            return this._findNearestTarget(npcEntityId);
        }

        // Validate provided target
        // Check entity ID format (must start with "ent-")
        if (!this._isValidEntityId(providedTargetId)) {
            return { ok: false, code: 'TARGET_NOT_FOUND', error: `Invalid entity id "${providedTargetId}"` };
        }

        // Check entity exists
        const target = this._facade.getEntity(providedTargetId);
        if (!target) {
            return { ok: false, code: 'TARGET_NOT_FOUND', error: `Entity "${providedTargetId}" not found` };
        }

        // Not self
        if (providedTargetId === npcEntityId) {
            return { ok: false, code: 'CANNOT_TARGET_SELF', error: 'Cannot target self' };
        }

        // Same room
        const npc = this._facade.getEntity(npcEntityId);
        if (!npc || !target || npc.location !== target.location) {
            return { ok: false, code: 'TARGET_NOT_IN_YOUR_ROOM', error: 'Target not in your room' };
        }

        // Finite spatial coords
        if (!isFiniteSpatial(target.spatial)) {
            return { ok: false, code: 'TARGET_NOT_FOUND', error: 'Target has non-finite spatial coords' };
        }

        return { ok: true, entity: target, entityId: providedTargetId };
    }

    /**
     * Check if a string is a valid entity ID format.
     * @param {string} id
     * @returns {boolean}
     */
    _isValidEntityId(id) {
        return isPrefixed(id, ID_PREFIXES.ENTITY);
    }

    /**
     * Find nearest eligible entity in the same room.
     * @param {string} npcEntityId
     * @returns {{ ok: boolean, entity?: Object, entityId?: string|null, code?: string, error?: string }}
     */
    _findNearestTarget(npcEntityId) {
        const npc = this._facade.getEntity(npcEntityId);
        if (!npc || !npc.location) {
            return { ok: false, code: 'NO_TARGET_IN_YOUR_ROOM', error: 'NPC has no room' };
        }

        const allEntities = this._facade.getEntities();
        if (!allEntities || allEntities.length === 0) {
            return { ok: false, code: 'NO_TARGET_IN_YOUR_ROOM', error: 'No entities in room' };
        }

        // Filter candidates: same room, finite spatial, not self
        const npcSpatial = npc.spatial;
        if (!isFiniteSpatial(npcSpatial)) {
            return { ok: false, code: 'NO_TARGET_IN_YOUR_ROOM', error: 'NPC has non-finite spatial' };
        }

        let nearest = null;
        let nearestDist = Infinity;
        let nearestId = null;

        for (const entity of allEntities) {
            if (!entity || entity.id === npcEntityId) continue;
            if (!entity.location || entity.location !== npc.location) continue;
            if (!isFiniteSpatial(entity.spatial)) continue;

            const d = Math.hypot(entity.spatial.x - npcSpatial.x, entity.spatial.y - npcSpatial.y);

            // Tie-break: ascending entityId (deterministic)
            if (d < nearestDist || (d === nearestDist && (!nearestId || entity.id < nearestId))) {
                nearestDist = d;
                nearest = entity;
                nearestId = entity.id;
            }
        }

        if (!nearest) {
            return { ok: false, code: 'NO_TARGET_IN_YOUR_ROOM', error: 'No eligible target in room' };
        }

        return { ok: true, entity: nearest, entityId: nearestId };
    }
}

export default InstinctController;
export { ROLE_WORDS, TEMPLATES, MAX_INSTINCT_STEPS };
